Retrieving logs for app dse-sample-app in org datastax / space pks as admin...

   2019-11-01T14:53:03.14-0700 [APP/PROC/WEB/0] OUT 21:53:03.142 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.185 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.186 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.186 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T14:53:03.18-0700 [APP/PROC/WEB/0] OUT 21:53:03.186 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T14:53:03.21-0700 [APP/PROC/WEB/0] OUT 21:53:03.215 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 14 (auto-detected)
   2019-11-01T14:53:03.21-0700 [APP/PROC/WEB/0] OUT 21:53:03.218 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T14:53:03.21-0700 [APP/PROC/WEB/0] OUT 21:53:03.218 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T14:53:03.22-0700 [APP/PROC/WEB/0] OUT 21:53:03.220 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T14:53:03.22-0700 [APP/PROC/WEB/0] OUT 21:53:03.220 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T14:53:03.22-0700 [APP/PROC/WEB/0] OUT 21:53:03.222 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:a4:d0 (auto-detected)
   2019-11-01T14:53:03.25-0700 [APP/PROC/WEB/0] OUT 21:53:03.250 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T14:53:03.25-0700 [APP/PROC/WEB/0] OUT 21:53:03.250 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T14:53:03.25-0700 [APP/PROC/WEB/0] OUT 21:53:03.251 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T14:53:08.31-0700 [APP/PROC/WEB/0] OUT 21:53:08.316 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 21:53:08.319 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 21:53:08.320 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 21:53:08.320 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 21:53:08.321 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 21:53:08.328 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T14:53:08.32-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T14:53:08.33-0700 [APP/PROC/WEB/0] OUT 21:53:08.330 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T14:53:08.34-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T14:53:11.62-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T14:53:11.62-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T14:53:17.27-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 stopping instance fb870122-7220-45a8-78d8-a999
   2019-11-01T14:53:17.27-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 destroying container for instance fb870122-7220-45a8-78d8-a999
   2019-11-01T14:53:17.28-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T14:53:17.29-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"fb870122-7220-45a8-78d8-a999", "index"=>0, "cell_id"=>"cd34d23c-cfaf-40fa-a608-5e5d7196f8c5", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>3, "crash_timestamp"=>1572645197271211981, "version"=>"2b414e3d-6b96-481c-9a1b-b7a608625ab9"}
   2019-11-01T14:53:17.51-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T14:53:17.65-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 successfully destroyed container for instance fb870122-7220-45a8-78d8-a999
   2019-11-01T14:54:04.36-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance aacbcd3c-f0f1-4739-4986-c87b
   2019-11-01T14:54:04.99-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance aacbcd3c-f0f1-4739-4986-c87b
   2019-11-01T14:54:05.52-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T14:54:06.05-0700 [CELL/0] OUT Downloaded droplet
   2019-11-01T14:54:06.33-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T14:54:08.12-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T14:54:08.52-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T14:54:08.72-0700 [APP/PROC/WEB/0] OUT 21:54:08.717 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T14:54:08.74-0700 [APP/PROC/WEB/0] OUT 21:54:08.742 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T14:54:08.74-0700 [APP/PROC/WEB/0] OUT 21:54:08.744 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T14:54:08.74-0700 [APP/PROC/WEB/0] OUT 21:54:08.744 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T14:54:08.78-0700 [APP/PROC/WEB/0] OUT 21:54:08.781 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T14:54:09.19-0700 [APP/PROC/WEB/0] OUT 21:54:09.195 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T14:54:09.22-0700 [APP/PROC/WEB/0] OUT 21:54:09.221 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T14:54:09.82-0700 [APP/PROC/WEB/0] OUT 21:54:09.826 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 20
   2019-11-01T14:54:09.84-0700 [APP/PROC/WEB/0] OUT 21:54:09.843 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 5492f411-891f-4d4b-9655-1e3f3f5de7d1) with contact points [/10.200.59.25:9042]
   2019-11-01T14:54:09.92-0700 [APP/PROC/WEB/0] OUT 21:54:09.927 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T14:54:09.96-0700 [APP/PROC/WEB/0] OUT 21:54:09.964 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T14:54:09.97-0700 [APP/PROC/WEB/0] OUT 21:54:09.971 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T14:54:10.00-0700 [APP/PROC/WEB/0] OUT 21:54:10.007 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T14:54:10.00-0700 [APP/PROC/WEB/0] OUT 21:54:10.008 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T14:54:10.01-0700 [APP/PROC/WEB/0] OUT 21:54:10.010 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T14:54:10.01-0700 [APP/PROC/WEB/0] OUT 21:54:10.012 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T14:54:10.01-0700 [APP/PROC/WEB/0] OUT 21:54:10.013 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T14:54:10.01-0700 [APP/PROC/WEB/0] OUT 21:54:10.014 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T14:54:10.02-0700 [APP/PROC/WEB/0] OUT 21:54:10.023 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T14:54:10.02-0700 [APP/PROC/WEB/0] OUT 21:54:10.023 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T14:54:10.02-0700 [APP/PROC/WEB/0] OUT 21:54:10.023 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T14:54:10.02-0700 [APP/PROC/WEB/0] OUT 21:54:10.023 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.031 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.031 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.033 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.034 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.035 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T14:54:10.03-0700 [APP/PROC/WEB/0] OUT 21:54:10.036 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T14:54:10.04-0700 [APP/PROC/WEB/0] OUT 21:54:10.041 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T14:54:10.04-0700 [APP/PROC/WEB/0] OUT 21:54:10.044 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T14:54:10.05-0700 [APP/PROC/WEB/0] OUT 21:54:10.057 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T14:54:10.07-0700 [APP/PROC/WEB/0] OUT 21:54:10.071 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T14:54:10.07-0700 [APP/PROC/WEB/0] OUT 21:54:10.071 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T14:54:10.08-0700 [APP/PROC/WEB/0] OUT 21:54:10.086 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T14:54:10.11-0700 [APP/PROC/WEB/0] OUT 21:54:10.113 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T14:54:10.11-0700 [APP/PROC/WEB/0] OUT 21:54:10.114 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T14:54:10.12-0700 [APP/PROC/WEB/0] OUT 21:54:10.119 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T14:54:10.13-0700 [APP/PROC/WEB/0] OUT 21:54:10.130 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T14:54:10.18-0700 [APP/PROC/WEB/0] OUT 21:54:10.187 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T14:54:10.19-0700 [APP/PROC/WEB/0] OUT 21:54:10.192 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T14:54:10.19-0700 [APP/PROC/WEB/0] OUT 21:54:10.193 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T14:54:10.19-0700 [APP/PROC/WEB/0] OUT 21:54:10.193 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.244 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.244 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.245 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.245 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.246 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.246 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.246 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.246 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.246 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.247 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.247 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.247 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T14:54:10.24-0700 [APP/PROC/WEB/0] OUT 21:54:10.248 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T14:54:10.28-0700 [APP/PROC/WEB/0] OUT 21:54:10.280 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 20 (auto-detected)
   2019-11-01T14:54:10.28-0700 [APP/PROC/WEB/0] OUT 21:54:10.285 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T14:54:10.28-0700 [APP/PROC/WEB/0] OUT 21:54:10.285 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T14:54:10.28-0700 [APP/PROC/WEB/0] OUT 21:54:10.287 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T14:54:10.29-0700 [APP/PROC/WEB/0] OUT 21:54:10.289 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T14:54:10.29-0700 [APP/PROC/WEB/0] OUT 21:54:10.292 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:6a:a5 (auto-detected)
   2019-11-01T14:54:10.32-0700 [APP/PROC/WEB/0] OUT 21:54:10.328 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T14:54:10.32-0700 [APP/PROC/WEB/0] OUT 21:54:10.329 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T14:54:10.33-0700 [APP/PROC/WEB/0] OUT 21:54:10.331 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T14:54:15.38-0700 [APP/PROC/WEB/0] OUT 21:54:15.386 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 21:54:15.390 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 21:54:15.391 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 21:54:15.392 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 21:54:15.392 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 21:54:15.398 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T14:54:15.39-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T14:54:15.40-0700 [APP/PROC/WEB/0] OUT 21:54:15.400 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T14:54:15.41-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T14:54:17.66-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T14:54:17.67-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T14:54:22.92-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance aacbcd3c-f0f1-4739-4986-c87b
   2019-11-01T14:54:22.92-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance aacbcd3c-f0f1-4739-4986-c87b
   2019-11-01T14:54:22.93-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T14:54:22.94-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"aacbcd3c-f0f1-4739-4986-c87b", "index"=>0, "cell_id"=>"6b2e01ef-168d-497a-a28f-07d1cb16a115", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>4, "crash_timestamp"=>1572645262919568265, "version"=>"2b414e3d-6b96-481c-9a1b-b7a608625ab9"}
   2019-11-01T14:54:23.10-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T14:54:23.26-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance aacbcd3c-f0f1-4739-4986-c87b
   2019-11-01T14:55:34.45-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance 5c3358bd-9225-49a3-5365-5f19
   2019-11-01T14:55:35.19-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance 5c3358bd-9225-49a3-5365-5f19
   2019-11-01T14:55:36.00-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T14:55:36.51-0700 [CELL/0] OUT Downloaded droplet
   2019-11-01T14:55:36.78-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T14:55:38.42-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T14:55:38.89-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T14:55:39.10-0700 [APP/PROC/WEB/0] OUT 21:55:39.100 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T14:55:39.12-0700 [APP/PROC/WEB/0] OUT 21:55:39.121 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T14:55:39.12-0700 [APP/PROC/WEB/0] OUT 21:55:39.123 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T14:55:39.12-0700 [APP/PROC/WEB/0] OUT 21:55:39.123 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T14:55:39.16-0700 [APP/PROC/WEB/0] OUT 21:55:39.160 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T14:55:39.55-0700 [APP/PROC/WEB/0] OUT 21:55:39.557 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T14:55:39.57-0700 [APP/PROC/WEB/0] OUT 21:55:39.575 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T14:55:39.92-0700 [APP/PROC/WEB/0] OUT 21:55:39.925 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 19
   2019-11-01T14:55:39.93-0700 [APP/PROC/WEB/0] OUT 21:55:39.933 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: cda682de-ab20-4e25-8df6-fb5d071d9ef0) with contact points [/10.200.59.25:9042]
   2019-11-01T14:55:39.98-0700 [APP/PROC/WEB/0] OUT 21:55:39.988 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T14:55:40.00-0700 [APP/PROC/WEB/0] OUT 21:55:40.005 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T14:55:40.00-0700 [APP/PROC/WEB/0] OUT 21:55:40.005 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.029 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.030 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.031 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.032 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.032 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.033 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.035 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.035 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.035 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.035 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.036 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T14:55:40.03-0700 [APP/PROC/WEB/0] OUT 21:55:40.036 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T14:55:40.04-0700 [APP/PROC/WEB/0] OUT 21:55:40.038 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T14:55:40.04-0700 [APP/PROC/WEB/0] OUT 21:55:40.038 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T14:55:40.04-0700 [APP/PROC/WEB/0] OUT 21:55:40.040 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T14:55:40.04-0700 [APP/PROC/WEB/0] OUT 21:55:40.040 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T14:55:40.05-0700 [APP/PROC/WEB/0] OUT 21:55:40.054 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T14:55:40.06-0700 [APP/PROC/WEB/0] OUT 21:55:40.064 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T14:55:40.09-0700 [APP/PROC/WEB/0] OUT 21:55:40.092 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T14:55:40.29-0700 [APP/PROC/WEB/0] OUT 21:55:40.290 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T14:55:40.30-0700 [APP/PROC/WEB/0] OUT 21:55:40.294 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T14:55:40.36-0700 [APP/PROC/WEB/0] OUT 21:55:40.364 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T14:55:40.38-0700 [APP/PROC/WEB/0] OUT 21:55:40.388 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T14:55:40.38-0700 [APP/PROC/WEB/0] OUT 21:55:40.388 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T14:55:40.39-0700 [APP/PROC/WEB/0] OUT 21:55:40.392 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T14:55:40.40-0700 [APP/PROC/WEB/0] OUT 21:55:40.402 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T14:55:40.46-0700 [APP/PROC/WEB/0] OUT 21:55:40.461 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T14:55:40.46-0700 [APP/PROC/WEB/0] OUT 21:55:40.465 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T14:55:40.46-0700 [APP/PROC/WEB/0] OUT 21:55:40.466 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T14:55:40.47-0700 [APP/PROC/WEB/0] OUT 21:55:40.466 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.526 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.526 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.527 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.528 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.528 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T14:55:40.52-0700 [APP/PROC/WEB/0] OUT 21:55:40.528 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T14:55:40.56-0700 [APP/PROC/WEB/0] OUT 21:55:40.561 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 19 (auto-detected)
   2019-11-01T14:55:40.56-0700 [APP/PROC/WEB/0] OUT 21:55:40.565 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T14:55:40.56-0700 [APP/PROC/WEB/0] OUT 21:55:40.565 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T14:55:40.56-0700 [APP/PROC/WEB/0] OUT 21:55:40.567 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T14:55:40.56-0700 [APP/PROC/WEB/0] OUT 21:55:40.568 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T14:55:40.57-0700 [APP/PROC/WEB/0] OUT 21:55:40.570 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:6a:a6 (auto-detected)
   2019-11-01T14:55:40.60-0700 [APP/PROC/WEB/0] OUT 21:55:40.602 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T14:55:40.60-0700 [APP/PROC/WEB/0] OUT 21:55:40.603 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T14:55:40.60-0700 [APP/PROC/WEB/0] OUT 21:55:40.606 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T14:55:45.68-0700 [APP/PROC/WEB/0] OUT 21:55:45.683 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T14:55:45.68-0700 [APP/PROC/WEB/0] OUT 21:55:45.687 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:55:45.68-0700 [APP/PROC/WEB/0] OUT 21:55:45.688 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T14:55:45.68-0700 [APP/PROC/WEB/0] OUT 21:55:45.688 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T14:55:45.68-0700 [APP/PROC/WEB/0] OUT 21:55:45.689 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 21:55:45.695 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T14:55:45.69-0700 [APP/PROC/WEB/0] OUT 21:55:45.696 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T14:55:45.71-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T14:55:47.97-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T14:55:47.97-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T14:55:53.50-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance 5c3358bd-9225-49a3-5365-5f19
   2019-11-01T14:55:53.50-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance 5c3358bd-9225-49a3-5365-5f19
   2019-11-01T14:55:53.51-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T14:55:53.52-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"5c3358bd-9225-49a3-5365-5f19", "index"=>0, "cell_id"=>"6b2e01ef-168d-497a-a28f-07d1cb16a115", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>5, "crash_timestamp"=>1572645353497676072, "version"=>"2b414e3d-6b96-481c-9a1b-b7a608625ab9"}
   2019-11-01T14:55:53.68-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T14:55:53.86-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance 5c3358bd-9225-49a3-5365-5f19
   2019-11-01T14:58:04.57-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance d2eb0ca4-3780-42b0-78ac-d3e2
   2019-11-01T14:58:05.28-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance d2eb0ca4-3780-42b0-78ac-d3e2
   2019-11-01T14:58:05.46-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T14:58:05.98-0700 [CELL/0] OUT Downloaded droplet
   2019-11-01T14:58:06.25-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T14:58:08.14-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T14:58:08.85-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T14:58:09.28-0700 [APP/PROC/WEB/0] OUT 21:58:09.280 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T14:58:09.36-0700 [APP/PROC/WEB/0] OUT 21:58:09.354 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T14:58:09.36-0700 [APP/PROC/WEB/0] OUT 21:58:09.361 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T14:58:09.36-0700 [APP/PROC/WEB/0] OUT 21:58:09.363 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T14:58:09.45-0700 [APP/PROC/WEB/0] OUT 21:58:09.455 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T14:58:10.00-0700 [APP/PROC/WEB/0] OUT 21:58:10.007 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T14:58:10.03-0700 [APP/PROC/WEB/0] OUT 21:58:10.029 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T14:58:10.40-0700 [APP/PROC/WEB/0] OUT 21:58:10.406 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 14
   2019-11-01T14:58:10.41-0700 [APP/PROC/WEB/0] OUT 21:58:10.416 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 850bd71e-d545-48e1-aa82-03884a482a65) with contact points [/10.200.59.25:9042]
   2019-11-01T14:58:10.45-0700 [APP/PROC/WEB/0] OUT 21:58:10.458 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T14:58:10.47-0700 [APP/PROC/WEB/0] OUT 21:58:10.475 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T14:58:10.47-0700 [APP/PROC/WEB/0] OUT 21:58:10.475 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T14:58:10.50-0700 [APP/PROC/WEB/0] OUT 21:58:10.499 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T14:58:10.50-0700 [APP/PROC/WEB/0] OUT 21:58:10.508 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T14:58:10.51-0700 [APP/PROC/WEB/0] OUT 21:58:10.510 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T14:58:10.51-0700 [APP/PROC/WEB/0] OUT 21:58:10.512 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T14:58:10.51-0700 [APP/PROC/WEB/0] OUT 21:58:10.513 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T14:58:10.51-0700 [APP/PROC/WEB/0] OUT 21:58:10.514 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T14:58:10.51-0700 [APP/PROC/WEB/0] OUT 21:58:10.515 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.523 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.523 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.524 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.526 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.526 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.528 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T14:58:10.52-0700 [APP/PROC/WEB/0] OUT 21:58:10.528 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T14:58:10.53-0700 [APP/PROC/WEB/0] OUT 21:58:10.530 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T14:58:10.53-0700 [APP/PROC/WEB/0] OUT 21:58:10.530 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T14:58:10.54-0700 [APP/PROC/WEB/0] OUT 21:58:10.543 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T14:58:10.54-0700 [APP/PROC/WEB/0] OUT 21:58:10.547 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T14:58:10.56-0700 [APP/PROC/WEB/0] OUT 21:58:10.559 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T14:58:10.57-0700 [APP/PROC/WEB/0] OUT 21:58:10.578 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T14:58:10.57-0700 [APP/PROC/WEB/0] OUT 21:58:10.579 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T14:58:10.59-0700 [APP/PROC/WEB/0] OUT 21:58:10.591 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T14:58:10.61-0700 [APP/PROC/WEB/0] OUT 21:58:10.613 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T14:58:10.61-0700 [APP/PROC/WEB/0] OUT 21:58:10.613 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T14:58:10.61-0700 [APP/PROC/WEB/0] OUT 21:58:10.617 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T14:58:10.62-0700 [APP/PROC/WEB/0] OUT 21:58:10.626 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T14:58:10.77-0700 [APP/PROC/WEB/0] OUT 21:58:10.775 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T14:58:10.77-0700 [APP/PROC/WEB/0] OUT 21:58:10.779 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T14:58:10.77-0700 [APP/PROC/WEB/0] OUT 21:58:10.779 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T14:58:10.77-0700 [APP/PROC/WEB/0] OUT 21:58:10.779 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.818 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T14:58:10.81-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T14:58:10.82-0700 [APP/PROC/WEB/0] OUT 21:58:10.819 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T14:58:10.82-0700 [APP/PROC/WEB/0] OUT 21:58:10.820 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T14:58:10.82-0700 [APP/PROC/WEB/0] OUT 21:58:10.820 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T14:58:10.82-0700 [APP/PROC/WEB/0] OUT 21:58:10.820 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.852 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 14 (auto-detected)
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.855 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.855 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.856 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.857 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T14:58:10.85-0700 [APP/PROC/WEB/0] OUT 21:58:10.859 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:6a:a7 (auto-detected)
   2019-11-01T14:58:10.88-0700 [APP/PROC/WEB/0] OUT 21:58:10.888 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T14:58:10.88-0700 [APP/PROC/WEB/0] OUT 21:58:10.888 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T14:58:10.88-0700 [APP/PROC/WEB/0] OUT 21:58:10.888 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T14:58:15.96-0700 [APP/PROC/WEB/0] OUT 21:58:15.962 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T14:58:15.96-0700 [APP/PROC/WEB/0] OUT 21:58:15.966 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:58:15.96-0700 [APP/PROC/WEB/0] OUT 21:58:15.967 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T14:58:15.96-0700 [APP/PROC/WEB/0] OUT 21:58:15.968 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T14:58:15.96-0700 [APP/PROC/WEB/0] OUT 21:58:15.969 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 21:58:15.975 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T14:58:15.97-0700 [APP/PROC/WEB/0] OUT 21:58:15.977 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T14:58:15.99-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T14:58:18.26-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T14:58:18.26-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T14:58:23.80-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance d2eb0ca4-3780-42b0-78ac-d3e2
   2019-11-01T14:58:23.80-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance d2eb0ca4-3780-42b0-78ac-d3e2
   2019-11-01T14:58:23.82-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T14:58:23.82-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"d2eb0ca4-3780-42b0-78ac-d3e2", "index"=>0, "cell_id"=>"6b2e01ef-168d-497a-a28f-07d1cb16a115", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>6, "crash_timestamp"=>1572645503805397855, "version"=>"2b414e3d-6b96-481c-9a1b-b7a608625ab9"}
   2019-11-01T14:58:23.98-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T14:58:24.15-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance d2eb0ca4-3780-42b0-78ac-d3e2
   2019-11-01T14:59:33.17-0700 [API/0] OUT Updated app with guid 69234102-7bc6-4792-a912-07be73ae176e ({"buildpack"=>"https://github.com/cloudfoundry/java-buildpack.git", "disk_quota"=>1024, "health_check_http_endpoint"=>"", "health_check_type"=>"port", "instances"=>1, "memory"=>2048, "name"=>"dse-sample-app", "space_guid"=>"46df64df-f65a-4ecd-84d3-6355b820f530"})
   2019-11-01T14:59:36.30-0700 [API/0] OUT Uploading bits for app with guid 69234102-7bc6-4792-a912-07be73ae176e
   2019-11-01T14:59:42.70-0700 [API/0] OUT Updated app with guid 69234102-7bc6-4792-a912-07be73ae176e ({"state"=>"STOPPED"})
   2019-11-01T14:59:42.93-0700 [API/0] OUT Creating build for app with guid 69234102-7bc6-4792-a912-07be73ae176e
   2019-11-01T14:59:43.02-0700 [API/0] OUT Updated app with guid 69234102-7bc6-4792-a912-07be73ae176e ({"state"=>"STARTED"})
   2019-11-01T14:59:43.04-0700 [STG/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance 050f900f-0ac3-4156-acd2-9b2652b36139
   2019-11-01T14:59:43.69-0700 [STG/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance 050f900f-0ac3-4156-acd2-9b2652b36139
   2019-11-01T14:59:44.17-0700 [STG/0] OUT Downloading app package...
   2019-11-01T14:59:44.17-0700 [STG/0] OUT Downloading build artifacts cache...
   2019-11-01T14:59:45.72-0700 [STG/0] OUT Downloaded build artifacts cache (42M)
   2019-11-01T14:59:45.78-0700 [STG/0] OUT Downloaded app package (28.4M)
   2019-11-01T14:59:48.91-0700 [STG/0] OUT [1m[31m----->[0m[22m [1m[34mJava Buildpack[0m[22m [34m349e93b[0m | https://github.com/cloudfoundry/java-buildpack.git#349e93b
   2019-11-01T14:59:49.12-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mJvmkill Agent[0m[22m [34m1.16.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so [3m[32m(found in cache)[0m[23m
   2019-11-01T14:59:49.19-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mOpen Jdk JRE[0m[22m [34m1.8.0_232[0m from https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-1.8.0_232-bionic.tar.gz [3m[32m(found in cache)[0m[23m
   2019-11-01T14:59:50.34-0700 [STG/0] OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre [3m[32m(1.1s)[0m[23m
   2019-11-01T14:59:50.34-0700 [STG/0] OUT        JVM DNS caching disabled in lieu of BOSH DNS caching
   2019-11-01T14:59:50.41-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mOpen JDK Like Memory Calculator[0m[22m [34m3.13.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-3.13.0-RELEASE.tar.gz [3m[32m(found in cache)[0m[23m
   2019-11-01T14:59:51.37-0700 [STG/0] OUT        Loaded Classes: 15345, Threads: 250
   2019-11-01T14:59:51.46-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mClient Certificate Mapper[0m[22m [34m1.11.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.11.0-RELEASE.jar [3m[32m(found in cache)[0m[23m
   2019-11-01T14:59:51.54-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mContainer Security Provider[0m[22m [34m1.16.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.16.0-RELEASE.jar [3m[32m(found in cache)[0m[23m
   2019-11-01T14:59:51.61-0700 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mSpring Auto Reconfiguration[0m[22m [34m2.11.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.11.0-RELEASE.jar [3m[32m(found in cache)[0m[23m
   2019-11-01T15:00:04.09-0700 [STG/0] OUT Exit status 0
   2019-11-01T15:00:04.09-0700 [STG/0] OUT Uploading droplet, build artifacts cache...
   2019-11-01T15:00:04.09-0700 [STG/0] OUT Uploading droplet...
   2019-11-01T15:00:04.09-0700 [STG/0] OUT Uploading build artifacts cache...
   2019-11-01T15:00:05.05-0700 [STG/0] OUT Uploaded build artifacts cache (42M)
   2019-11-01T15:00:05.35-0700 [API/0] OUT Creating droplet for app with guid 69234102-7bc6-4792-a912-07be73ae176e
   2019-11-01T15:00:08.56-0700 [STG/0] OUT Uploaded droplet (70.6M)
   2019-11-01T15:00:08.58-0700 [STG/0] OUT Uploading complete
   2019-11-01T15:00:08.86-0700 [STG/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance 050f900f-0ac3-4156-acd2-9b2652b36139
   2019-11-01T15:00:08.86-0700 [STG/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance 050f900f-0ac3-4156-acd2-9b2652b36139
   2019-11-01T15:00:09.08-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 creating container for instance 6ed0ab2e-50e7-49d0-4dc0-81c8
   2019-11-01T15:00:09.77-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 successfully created container for instance 6ed0ab2e-50e7-49d0-4dc0-81c8
   2019-11-01T15:00:09.99-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T15:00:11.18-0700 [STG/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance 050f900f-0ac3-4156-acd2-9b2652b36139
   2019-11-01T15:00:13.07-0700 [CELL/0] OUT Downloaded droplet (70.6M)
   2019-11-01T15:00:13.36-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T15:00:15.12-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T15:00:15.53-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T15:00:15.76-0700 [APP/PROC/WEB/0] OUT 22:00:15.754 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T15:00:15.77-0700 [APP/PROC/WEB/0] OUT 22:00:15.777 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T15:00:15.78-0700 [APP/PROC/WEB/0] OUT 22:00:15.779 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T15:00:15.78-0700 [APP/PROC/WEB/0] OUT 22:00:15.780 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T15:00:15.81-0700 [APP/PROC/WEB/0] OUT 22:00:15.814 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T15:00:16.20-0700 [APP/PROC/WEB/0] OUT 22:00:16.208 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T15:00:16.23-0700 [APP/PROC/WEB/0] OUT 22:00:16.230 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T15:00:16.83-0700 [APP/PROC/WEB/0] OUT 22:00:16.830 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 28
   2019-11-01T15:00:16.83-0700 [APP/PROC/WEB/0] OUT 22:00:16.834 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 43b93d72-99bc-4452-a90d-0dab84d825dd) with contact points [/10.200.59.25:9042]
   2019-11-01T15:00:16.91-0700 [APP/PROC/WEB/0] OUT 22:00:16.912 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T15:00:16.93-0700 [APP/PROC/WEB/0] OUT 22:00:16.934 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T15:00:16.93-0700 [APP/PROC/WEB/0] OUT 22:00:16.934 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T15:00:16.95-0700 [APP/PROC/WEB/0] OUT 22:00:16.958 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T15:00:16.95-0700 [APP/PROC/WEB/0] OUT 22:00:16.958 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T15:00:16.95-0700 [APP/PROC/WEB/0] OUT 22:00:16.959 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.960 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.960 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.961 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.962 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.962 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.962 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.962 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.963 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.963 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.965 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.965 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.966 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T15:00:16.96-0700 [APP/PROC/WEB/0] OUT 22:00:16.966 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T15:00:16.97-0700 [APP/PROC/WEB/0] OUT 22:00:16.972 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T15:00:16.97-0700 [APP/PROC/WEB/0] OUT 22:00:16.973 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T15:00:16.97-0700 [APP/PROC/WEB/0] OUT 22:00:16.978 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T15:00:16.99-0700 [APP/PROC/WEB/0] OUT 22:00:16.993 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T15:00:16.99-0700 [APP/PROC/WEB/0] OUT 22:00:16.994 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T15:00:17.00-0700 [APP/PROC/WEB/0] OUT 22:00:17.003 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T15:00:17.02-0700 [APP/PROC/WEB/0] OUT 22:00:17.022 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T15:00:17.02-0700 [APP/PROC/WEB/0] OUT 22:00:17.023 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T15:00:17.02-0700 [APP/PROC/WEB/0] OUT 22:00:17.026 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2de23121
   2019-11-01T15:00:17.03-0700 [APP/PROC/WEB/0] OUT 22:00:17.034 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T15:00:17.08-0700 [APP/PROC/WEB/0] OUT 22:00:17.079 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T15:00:17.08-0700 [APP/PROC/WEB/0] OUT 22:00:17.084 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T15:00:17.08-0700 [APP/PROC/WEB/0] OUT 22:00:17.085 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T15:00:17.08-0700 [APP/PROC/WEB/0] OUT 22:00:17.085 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.141 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.141 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.141 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.142 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.143 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.143 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.143 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.143 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T15:00:17.14-0700 [APP/PROC/WEB/0] OUT 22:00:17.144 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T15:00:17.17-0700 [APP/PROC/WEB/0] OUT 22:00:17.175 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 28 (auto-detected)
   2019-11-01T15:00:17.17-0700 [APP/PROC/WEB/0] OUT 22:00:17.178 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T15:00:17.17-0700 [APP/PROC/WEB/0] OUT 22:00:17.178 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T15:00:17.18-0700 [APP/PROC/WEB/0] OUT 22:00:17.180 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T15:00:17.18-0700 [APP/PROC/WEB/0] OUT 22:00:17.181 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T15:00:17.18-0700 [APP/PROC/WEB/0] OUT 22:00:17.184 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:a4:d2 (auto-detected)
   2019-11-01T15:00:17.21-0700 [APP/PROC/WEB/0] OUT 22:00:17.213 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T15:00:17.21-0700 [APP/PROC/WEB/0] OUT 22:00:17.214 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T15:00:17.21-0700 [APP/PROC/WEB/0] OUT 22:00:17.216 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T15:00:22.28-0700 [APP/PROC/WEB/0] OUT 22:00:22.284 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T15:00:22.28-0700 [APP/PROC/WEB/0] OUT 22:00:22.288 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:00:22.28-0700 [APP/PROC/WEB/0] OUT 22:00:22.289 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 22:00:22.289 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 22:00:22.290 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 22:00:22.297 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T15:00:22.29-0700 [APP/PROC/WEB/0] OUT 22:00:22.298 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T15:00:22.31-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T15:00:22.32-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T15:00:24.57-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T15:00:24.57-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T15:00:30.47-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 stopping instance 6ed0ab2e-50e7-49d0-4dc0-81c8
   2019-11-01T15:00:30.47-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 destroying container for instance 6ed0ab2e-50e7-49d0-4dc0-81c8
   2019-11-01T15:00:30.47-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T15:00:30.48-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"6ed0ab2e-50e7-49d0-4dc0-81c8", "index"=>0, "cell_id"=>"cd34d23c-cfaf-40fa-a608-5e5d7196f8c5", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>1, "crash_timestamp"=>1572645630453322553, "version"=>"b2776595-e9fa-4cea-90ec-648972d0887a"}
   2019-11-01T15:00:30.49-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance 9f574700-93c3-40ac-6657-0333
   2019-11-01T15:00:30.64-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T15:00:30.84-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 successfully destroyed container for instance 6ed0ab2e-50e7-49d0-4dc0-81c8
   2019-11-01T15:00:31.21-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance 9f574700-93c3-40ac-6657-0333
   2019-11-01T15:00:31.38-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T15:00:34.28-0700 [CELL/0] OUT Downloaded droplet (70.6M)
   2019-11-01T15:00:34.56-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T15:00:36.29-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T15:00:36.71-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T15:00:36.93-0700 [APP/PROC/WEB/0] OUT 22:00:36.930 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T15:00:36.95-0700 [APP/PROC/WEB/0] OUT 22:00:36.952 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T15:00:36.95-0700 [APP/PROC/WEB/0] OUT 22:00:36.953 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T15:00:36.95-0700 [APP/PROC/WEB/0] OUT 22:00:36.954 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T15:00:36.99-0700 [APP/PROC/WEB/0] OUT 22:00:36.996 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T15:00:37.36-0700 [APP/PROC/WEB/0] OUT 22:00:37.365 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T15:00:37.39-0700 [APP/PROC/WEB/0] OUT 22:00:37.390 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T15:00:37.86-0700 [APP/PROC/WEB/0] OUT 22:00:37.848 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 15
   2019-11-01T15:00:37.89-0700 [APP/PROC/WEB/0] OUT 22:00:37.897 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 04f977c2-a61d-4871-9fc1-57a50e657dcc) with contact points [/10.200.59.25:9042]
   2019-11-01T15:00:37.99-0700 [APP/PROC/WEB/0] OUT 22:00:37.996 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T15:00:38.03-0700 [APP/PROC/WEB/0] OUT 22:00:38.032 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T15:00:38.03-0700 [APP/PROC/WEB/0] OUT 22:00:38.032 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T15:00:38.05-0700 [APP/PROC/WEB/0] OUT 22:00:38.058 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T15:00:38.05-0700 [APP/PROC/WEB/0] OUT 22:00:38.059 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.061 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.062 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.063 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.064 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.066 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.066 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.067 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.067 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.068 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T15:00:38.06-0700 [APP/PROC/WEB/0] OUT 22:00:38.069 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T15:00:38.07-0700 [APP/PROC/WEB/0] OUT 22:00:38.070 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T15:00:38.07-0700 [APP/PROC/WEB/0] OUT 22:00:38.071 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T15:00:38.07-0700 [APP/PROC/WEB/0] OUT 22:00:38.072 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T15:00:38.07-0700 [APP/PROC/WEB/0] OUT 22:00:38.072 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T15:00:38.07-0700 [APP/PROC/WEB/0] OUT 22:00:38.079 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T15:00:38.08-0700 [APP/PROC/WEB/0] OUT 22:00:38.080 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T15:00:38.09-0700 [APP/PROC/WEB/0] OUT 22:00:38.091 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T15:00:38.10-0700 [APP/PROC/WEB/0] OUT 22:00:38.104 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T15:00:38.10-0700 [APP/PROC/WEB/0] OUT 22:00:38.104 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T15:00:38.11-0700 [APP/PROC/WEB/0] OUT 22:00:38.117 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T15:00:38.14-0700 [APP/PROC/WEB/0] OUT 22:00:38.140 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T15:00:38.14-0700 [APP/PROC/WEB/0] OUT 22:00:38.140 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T15:00:38.15-0700 [APP/PROC/WEB/0] OUT 22:00:38.150 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T15:00:38.15-0700 [APP/PROC/WEB/0] OUT 22:00:38.158 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T15:00:38.20-0700 [APP/PROC/WEB/0] OUT 22:00:38.207 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T15:00:38.23-0700 [APP/PROC/WEB/0] OUT 22:00:38.230 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T15:00:38.23-0700 [APP/PROC/WEB/0] OUT 22:00:38.230 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T15:00:38.23-0700 [APP/PROC/WEB/0] OUT 22:00:38.231 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.272 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T15:00:38.27-0700 [APP/PROC/WEB/0] OUT 22:00:38.273 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T15:00:38.30-0700 [APP/PROC/WEB/0] OUT 22:00:38.306 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 15 (auto-detected)
   2019-11-01T15:00:38.30-0700 [APP/PROC/WEB/0] OUT 22:00:38.309 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T15:00:38.31-0700 [APP/PROC/WEB/0] OUT 22:00:38.309 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T15:00:38.31-0700 [APP/PROC/WEB/0] OUT 22:00:38.311 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T15:00:38.31-0700 [APP/PROC/WEB/0] OUT 22:00:38.312 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T15:00:38.31-0700 [APP/PROC/WEB/0] OUT 22:00:38.314 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:6a:aa (auto-detected)
   2019-11-01T15:00:38.34-0700 [APP/PROC/WEB/0] OUT 22:00:38.345 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T15:00:38.34-0700 [APP/PROC/WEB/0] OUT 22:00:38.345 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T15:00:38.34-0700 [APP/PROC/WEB/0] OUT 22:00:38.345 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T15:00:43.41-0700 [APP/PROC/WEB/0] OUT 22:00:43.414 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T15:00:43.41-0700 [APP/PROC/WEB/0] OUT 22:00:43.417 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:00:43.41-0700 [APP/PROC/WEB/0] OUT 22:00:43.419 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T15:00:43.41-0700 [APP/PROC/WEB/0] OUT 22:00:43.419 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 22:00:43.420 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 22:00:43.427 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T15:00:43.42-0700 [APP/PROC/WEB/0] OUT 22:00:43.429 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T15:00:43.44-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T15:00:45.70-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T15:00:45.71-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T15:00:51.67-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance 9f574700-93c3-40ac-6657-0333
   2019-11-01T15:00:51.67-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance 9f574700-93c3-40ac-6657-0333
   2019-11-01T15:00:51.67-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T15:00:51.68-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"9f574700-93c3-40ac-6657-0333", "index"=>0, "cell_id"=>"6b2e01ef-168d-497a-a28f-07d1cb16a115", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>2, "crash_timestamp"=>1572645651653086878, "version"=>"b2776595-e9fa-4cea-90ec-648972d0887a"}
   2019-11-01T15:00:51.69-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 creating container for instance 6c2c7385-c3a8-489e-6b6b-7c78
   2019-11-01T15:00:51.85-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T15:00:52.01-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance 9f574700-93c3-40ac-6657-0333
   2019-11-01T15:00:52.41-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 successfully created container for instance 6c2c7385-c3a8-489e-6b6b-7c78
   2019-11-01T15:00:52.54-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T15:00:53.17-0700 [CELL/0] OUT Downloaded droplet
   2019-11-01T15:00:53.44-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T15:00:55.11-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T15:00:55.49-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T15:00:55.68-0700 [APP/PROC/WEB/0] OUT 22:00:55.676 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T15:00:55.69-0700 [APP/PROC/WEB/0] OUT 22:00:55.695 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T15:00:55.69-0700 [APP/PROC/WEB/0] OUT 22:00:55.696 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T15:00:55.69-0700 [APP/PROC/WEB/0] OUT 22:00:55.696 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T15:00:55.73-0700 [APP/PROC/WEB/0] OUT 22:00:55.738 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T15:00:56.08-0700 [APP/PROC/WEB/0] OUT 22:00:56.088 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T15:00:56.11-0700 [APP/PROC/WEB/0] OUT 22:00:56.110 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T15:00:56.44-0700 [APP/PROC/WEB/0] OUT 22:00:56.443 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 13
   2019-11-01T15:00:56.44-0700 [APP/PROC/WEB/0] OUT 22:00:56.449 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 7b5a016a-9f1f-4eb8-8735-2bf112a9677b) with contact points [/10.200.59.25:9042]
   2019-11-01T15:00:56.49-0700 [APP/PROC/WEB/0] OUT 22:00:56.490 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T15:00:56.52-0700 [APP/PROC/WEB/0] OUT 22:00:56.528 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T15:00:56.53-0700 [APP/PROC/WEB/0] OUT 22:00:56.532 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T15:00:56.64-0700 [APP/PROC/WEB/0] OUT 22:00:56.644 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T15:00:56.64-0700 [APP/PROC/WEB/0] OUT 22:00:56.644 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T15:00:56.64-0700 [APP/PROC/WEB/0] OUT 22:00:56.645 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.649 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.650 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.651 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.656 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.657 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.657 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T15:00:56.65-0700 [APP/PROC/WEB/0] OUT 22:00:56.658 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T15:00:56.66-0700 [APP/PROC/WEB/0] OUT 22:00:56.660 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T15:00:56.66-0700 [APP/PROC/WEB/0] OUT 22:00:56.662 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T15:00:56.69-0700 [APP/PROC/WEB/0] OUT 22:00:56.680 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.682 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.684 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.685 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.691 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.692 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T15:00:56.70-0700 [APP/PROC/WEB/0] OUT 22:00:56.699 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T15:00:56.77-0700 [APP/PROC/WEB/0] OUT 22:00:56.773 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T15:00:56.77-0700 [APP/PROC/WEB/0] OUT 22:00:56.774 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T15:00:56.83-0700 [APP/PROC/WEB/0] OUT 22:00:56.832 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T15:00:57.01-0700 [APP/PROC/WEB/0] OUT 22:00:57.010 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T15:00:57.01-0700 [APP/PROC/WEB/0] OUT 22:00:57.013 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T15:00:57.02-0700 [APP/PROC/WEB/0] OUT 22:00:57.028 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T15:00:57.06-0700 [APP/PROC/WEB/0] OUT 22:00:57.061 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T15:00:57.27-0700 [APP/PROC/WEB/0] OUT 22:00:57.279 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T15:00:57.28-0700 [APP/PROC/WEB/0] OUT 22:00:57.284 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T15:00:57.28-0700 [APP/PROC/WEB/0] OUT 22:00:57.284 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T15:00:57.28-0700 [APP/PROC/WEB/0] OUT 22:00:57.284 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T15:00:57.39-0700 [APP/PROC/WEB/0] OUT 22:00:57.397 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.397 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.399 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.399 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T15:00:57.40-0700 [APP/PROC/WEB/0] OUT 22:00:57.400 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T15:00:57.45-0700 [APP/PROC/WEB/0] OUT 22:00:57.455 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 13 (auto-detected)
   2019-11-01T15:00:57.45-0700 [APP/PROC/WEB/0] OUT 22:00:57.457 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T15:00:57.45-0700 [APP/PROC/WEB/0] OUT 22:00:57.458 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T15:00:57.46-0700 [APP/PROC/WEB/0] OUT 22:00:57.459 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T15:00:57.46-0700 [APP/PROC/WEB/0] OUT 22:00:57.460 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T15:00:57.46-0700 [APP/PROC/WEB/0] OUT 22:00:57.462 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:a4:d3 (auto-detected)
   2019-11-01T15:00:57.49-0700 [APP/PROC/WEB/0] OUT 22:00:57.493 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T15:00:57.49-0700 [APP/PROC/WEB/0] OUT 22:00:57.494 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T15:00:57.49-0700 [APP/PROC/WEB/0] OUT 22:00:57.495 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T15:01:02.56-0700 [APP/PROC/WEB/0] OUT 22:01:02.561 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T15:01:02.56-0700 [APP/PROC/WEB/0] OUT 22:01:02.564 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:01:02.56-0700 [APP/PROC/WEB/0] OUT 22:01:02.565 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T15:01:02.56-0700 [APP/PROC/WEB/0] OUT 22:01:02.565 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T15:01:02.56-0700 [APP/PROC/WEB/0] OUT 22:01:02.566 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 22:01:02.571 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T15:01:02.57-0700 [APP/PROC/WEB/0] OUT 22:01:02.572 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T15:01:02.58-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T15:01:02.58-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T15:01:02.58-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T15:01:02.58-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T15:01:02.59-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T15:01:05.84-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T15:01:05.84-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T15:01:11.29-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 stopping instance 6c2c7385-c3a8-489e-6b6b-7c78
   2019-11-01T15:01:11.29-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 destroying container for instance 6c2c7385-c3a8-489e-6b6b-7c78
   2019-11-01T15:01:11.30-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T15:01:11.31-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"6c2c7385-c3a8-489e-6b6b-7c78", "index"=>0, "cell_id"=>"cd34d23c-cfaf-40fa-a608-5e5d7196f8c5", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>3, "crash_timestamp"=>1572645671290792719, "version"=>"b2776595-e9fa-4cea-90ec-648972d0887a"}
   2019-11-01T15:01:11.53-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T15:01:11.69-0700 [CELL/0] OUT Cell cd34d23c-cfaf-40fa-a608-5e5d7196f8c5 successfully destroyed container for instance 6c2c7385-c3a8-489e-6b6b-7c78
   2019-11-01T15:02:04.75-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 creating container for instance 7732087f-8bbe-49a3-4013-84fb
   2019-11-01T15:02:05.50-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully created container for instance 7732087f-8bbe-49a3-4013-84fb
   2019-11-01T15:02:05.69-0700 [CELL/0] OUT Downloading droplet...
   2019-11-01T15:02:06.22-0700 [CELL/0] OUT Downloaded droplet
   2019-11-01T15:02:06.48-0700 [CELL/0] OUT Starting health monitoring of container
   2019-11-01T15:02:08.21-0700 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx1480141K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=105010K
   2019-11-01T15:02:08.59-0700 [APP/PROC/WEB/0] OUT ##### Has Cloud Properties #####
   2019-11-01T15:02:08.79-0700 [APP/PROC/WEB/0] OUT 22:02:08.790 [main] INFO com.datastax.driver.core - DataStax Java Driver 1.7.0 for DataStax Enterprise (DSE) and Apache Cassandra®
   2019-11-01T15:02:08.81-0700 [APP/PROC/WEB/0] OUT 22:02:08.809 [main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
   2019-11-01T15:02:08.81-0700 [APP/PROC/WEB/0] OUT 22:02:08.811 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
   2019-11-01T15:02:08.81-0700 [APP/PROC/WEB/0] OUT 22:02:08.811 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
   2019-11-01T15:02:08.83-0700 [APP/PROC/WEB/0] OUT 22:02:08.837 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
   2019-11-01T15:02:09.17-0700 [APP/PROC/WEB/0] OUT 22:02:09.174 [main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
   2019-11-01T15:02:09.19-0700 [APP/PROC/WEB/0] OUT 22:02:09.198 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2
   2019-11-01T15:02:09.79-0700 [APP/PROC/WEB/0] OUT 22:02:09.798 [main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 27
   2019-11-01T15:02:09.81-0700 [APP/PROC/WEB/0] OUT 22:02:09.811 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster (name: cluster1, id: 2e366cdb-4759-4760-958f-17b044d4dd19) with contact points [/10.200.59.25:9042]
   2019-11-01T15:02:09.88-0700 [APP/PROC/WEB/0] OUT 22:02:09.882 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
   2019-11-01T15:02:09.89-0700 [APP/PROC/WEB/0] OUT 22:02:09.897 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
   2019-11-01T15:02:09.89-0700 [APP/PROC/WEB/0] OUT 22:02:09.897 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.916 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.916 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.917 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.918 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.918 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
   2019-11-01T15:02:09.91-0700 [APP/PROC/WEB/0] OUT 22:02:09.919 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.920 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.920 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.920 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.920 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.921 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /home/vcap/tmp (java.io.tmpdir)
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.921 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.923 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 10485760 bytes
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.923 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.924 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.924 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.928 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
   2019-11-01T15:02:09.92-0700 [APP/PROC/WEB/0] OUT 22:02:09.929 [main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
   2019-11-01T15:02:09.93-0700 [APP/PROC/WEB/0] OUT 22:02:09.933 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
   2019-11-01T15:02:09.94-0700 [APP/PROC/WEB/0] OUT 22:02:09.945 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
   2019-11-01T15:02:09.94-0700 [APP/PROC/WEB/0] OUT 22:02:09.945 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
   2019-11-01T15:02:09.95-0700 [APP/PROC/WEB/0] OUT 22:02:09.955 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
   2019-11-01T15:02:09.97-0700 [APP/PROC/WEB/0] OUT 22:02:09.973 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
   2019-11-01T15:02:09.97-0700 [APP/PROC/WEB/0] OUT 22:02:09.974 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
   2019-11-01T15:02:09.97-0700 [APP/PROC/WEB/0] OUT 22:02:09.977 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4988d8b8
   2019-11-01T15:02:09.98-0700 [APP/PROC/WEB/0] OUT 22:02:09.987 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
   2019-11-01T15:02:10.05-0700 [APP/PROC/WEB/0] OUT 22:02:10.054 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preparing to open 1 new connections, total = 1
   2019-11-01T15:02:10.05-0700 [APP/PROC/WEB/0] OUT 22:02:10.058 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
   2019-11-01T15:02:10.05-0700 [APP/PROC/WEB/0] OUT 22:02:10.059 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
   2019-11-01T15:02:10.05-0700 [APP/PROC/WEB/0] OUT 22:02:10.059 [main] DEBUG com.datastax.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
   2019-11-01T15:02:10.10-0700 [APP/PROC/WEB/0] OUT 22:02:10.109 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.109 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.110 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.111 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.111 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.111 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.111 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.111 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.112 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.112 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.112 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.112 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
   2019-11-01T15:02:10.11-0700 [APP/PROC/WEB/0] OUT 22:02:10.112 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
   2019-11-01T15:02:10.14-0700 [APP/PROC/WEB/0] OUT 22:02:10.142 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 27 (auto-detected)
   2019-11-01T15:02:10.14-0700 [APP/PROC/WEB/0] OUT 22:02:10.145 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
   2019-11-01T15:02:10.14-0700 [APP/PROC/WEB/0] OUT 22:02:10.146 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
   2019-11-01T15:02:10.14-0700 [APP/PROC/WEB/0] OUT 22:02:10.148 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
   2019-11-01T15:02:10.14-0700 [APP/PROC/WEB/0] OUT 22:02:10.149 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
   2019-11-01T15:02:10.15-0700 [APP/PROC/WEB/0] OUT 22:02:10.151 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ee:ee:0a:ff:fe:ff:6a:ab (auto-detected)
   2019-11-01T15:02:10.18-0700 [APP/PROC/WEB/0] OUT 22:02:10.185 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
   2019-11-01T15:02:10.18-0700 [APP/PROC/WEB/0] OUT 22:02:10.185 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
   2019-11-01T15:02:10.18-0700 [APP/PROC/WEB/0] OUT 22:02:10.185 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
   2019-11-01T15:02:15.25-0700 [APP/PROC/WEB/0] OUT 22:02:15.252 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] Error connecting to /10.200.59.25:9042 (connection timed out: /10.200.59.25:9042)
   2019-11-01T15:02:15.25-0700 [APP/PROC/WEB/0] OUT 22:02:15.255 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] because: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:02:15.25-0700 [APP/PROC/WEB/0] OUT 22:02:15.257 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] preventing new connections for the next 1000 ms
   2019-11-01T15:02:15.25-0700 [APP/PROC/WEB/0] OUT 22:02:15.257 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.200.59.25:9042] Connection[/10.200.59.25:9042-1, inFlight=0, closed=false] failed, remaining = 0
   2019-11-01T15:02:15.25-0700 [APP/PROC/WEB/0] OUT 22:02:15.258 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.200.59.25:9042-1, inFlight=0, closed=true] closing connection
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 22:02:15.263 [main] DEBUG com.datastax.driver.core.ControlConnection - [Control connection] error on /10.200.59.25:9042 connection, no more host to try
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:215)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:185)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.200.59.25:9042
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 	... 9 common frames omitted
   2019-11-01T15:02:15.26-0700 [APP/PROC/WEB/0] OUT 22:02:15.265 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down
   2019-11-01T15:02:15.27-0700 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-11-01T15:02:15.27-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-11-01T15:02:15.27-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-11-01T15:02:15.27-0700 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.200.59.25:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.200.59.25:9042] Cannot connect))
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1687)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1606)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:453)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.DseSession.<init>(DseSession.java:100)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	at com.datastax.sampleapp.SampleAppApplication.main(SampleAppApplication.java:23)
   2019-11-01T15:02:15.28-0700 [APP/PROC/WEB/0] ERR 	... 8 more
   2019-11-01T15:02:17.54-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2019-11-01T15:02:17.54-0700 [CELL/SSHD/0] OUT Exit status 0
   2019-11-01T15:02:22.89-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 stopping instance 7732087f-8bbe-49a3-4013-84fb
   2019-11-01T15:02:22.89-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 destroying container for instance 7732087f-8bbe-49a3-4013-84fb
   2019-11-01T15:02:22.91-0700 [API/0] OUT Process has crashed with type: "web"
   2019-11-01T15:02:22.92-0700 [API/0] OUT App instance exited with guid 69234102-7bc6-4792-a912-07be73ae176e payload: {"instance"=>"7732087f-8bbe-49a3-4013-84fb", "index"=>0, "cell_id"=>"6b2e01ef-168d-497a-a28f-07d1cb16a115", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>4, "crash_timestamp"=>1572645742894761002, "version"=>"b2776595-e9fa-4cea-90ec-648972d0887a"}
   2019-11-01T15:02:23.09-0700 [PROXY/0] OUT Exit status 137
   2019-11-01T15:02:23.27-0700 [CELL/0] OUT Cell 6b2e01ef-168d-497a-a28f-07d1cb16a115 successfully destroyed container for instance 7732087f-8bbe-49a3-4013-84fb
